### ISSUE TITLE
error

### ISSUE THREAD

**Issue by soleHats** [guiguan/iphone-x-preorder-helper#1]
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

**Comment by guiguan** [comment]
You may need to install node >= 7.10.1

**Comment by soleHats** [comment]
im i doing right?

await page.type('#login-appleId', appleorder@gmail.com);
                                                 ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:576:28)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by guiguan** [comment]
You need to quote your email as a string:
`await page.type('#login-appleId', 'appleorder@gmail.com');`

Also, check your `node` version:
`node -v`, make sure it is >= 7.10.1

**Comment by soleHats** [comment]
yea its all good now tnx mate
